=== DrizztLei/code/work/XML/Lab 4 - Namespaces/test.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
		This XMLSchema is used to enforce namespace adherence
     in the Namespaces lab. Please do not change it.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns="http://www.ibm.com/ILS/WDO3"
   targetNamespace="http://www.ibm.com/ILS/WDO3" elementFormDefault="qualified">
   <xsd:complexType name="choiceType">
      <xsd:choice>
         <xsd:sequence>
            <xsd:element ref="choiceText"/>
            <xsd:element ref="correct"/>
         </xsd:sequence>
         <xsd:sequence>
            <xsd:element ref="correct"/>
            <xsd:element ref="choiceText"/>
         </xsd:sequence>
      </xsd:choice>
      <xsd:attribute name="id" type="xsd:ID" use="required"/>
   </xsd:complexType>
   <xsd:element name="choiceText" type="xsd:string"/>
   <xsd:complexType name="choicesType">
      <xsd:sequence>
         <xsd:element name="choice" type="choiceType"
            maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="allowMultiple" default="No">
         <xsd:simpleType>
            <xsd:restriction base="xsd:NMTOKEN">
               <xsd:enumeration value="Yes"/>
               <xsd:enumeration value="No"/>
            </xsd:restriction>
         </xsd:simpleType>
      </xsd:attribute>
   </xsd:complexType>
   <xsd:element name="correct" type="xsd:boolean"/>
   <xsd:element name="description" type="xsd:string"/>
   <xsd:complexType name="questionType">
      <xsd:sequence>
         <xsd:element name="questionText" type="xsd:string"/>
         <xsd:element name="choices" type="choicesType"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:ID" use="required"/>
   </xsd:complexType>
   <xsd:element name="test">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref="description"/>
               maxOccurs="unbounded"/>
            <xsd:element name="testQuestions" type="testQuestionsType"/>
         </xsd:sequence>
         <xsd:attribute name="id" type="xsd:ID" use="required"/>
      </xsd:complexType>
   </xsd:element>
   <xsd:complexType name="testQuestionsType">
      <xsd:sequence>
         <xsd:element name="question" type="questionType"
            maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== DrizztLei/code/work/XML/Lab 4 - Namespaces/ns.xml
<?xml version="1.0" encoding="US-ASCII"?>

<ns1:test id="XM30_Namespaces" xmlns:ns1="http://www.ibm.com/ILS/WDO3"
          xmlns="http://www.ibm.com/ILS/WDO3"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.ibm.com/ILS/WDO3 test.xsd ">

    <!-- Please do not change the xsi namespace declaration
         or the schemaLocation attribute -->

    <description>XML Namespaces Test</description>
    <ns1:testQuestions>
        <ns1:question id="Q1">
            <ns1:questionText>
                Which are true about XML Namespaces
            </ns1:questionText>
            <ns1:choices allowMultiple="Yes">
                <ns2:choice id="A"
                            xmlns:ns1="http://www.ibm.com/ILS/general"
                            xmlns:ns2="http://www.ibm.com/ILS/WDO3">
                    <ns2:choiceText>
                        XML Namespaces are assocated with an XML Schema
                    </ns2:choiceText>
                    <ns2:correct>false</ns2:correct>
                </ns2:choice>
                <ns1:choice id="B">
                    <ns1:choiceText>
                        XML Namespaces can be dereferenced
                    </ns1:choiceText>
                    <ns1:correct>false</ns1:correct>
                </ns1:choice>
                <ns1:choice id="C">
                    <ns1:choiceText>
                        XML Namespaces are associated with a URI
                    </ns1:choiceText>
                    <ns1:correct>true</ns1:correct>
                </ns1:choice>
                <ns1:choice id="D">
                    <ns1:choiceText></ns1:choiceText>
                    <ns1:correct>false</ns1:correct>
                </ns1:choice>
            </ns1:choices>
        </ns1:question>
    </ns1:testQuestions>
</ns1:test>
